/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWasteReportsRouteImport } from './routes/_authenticated/waste-reports'
import { Route as AuthenticatedWasteCollectionRouteImport } from './routes/_authenticated/waste-collection'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedOrderHistoryRouteImport } from './routes/_authenticated/order-history'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedGisMapRouteImport } from './routes/_authenticated/gis-map'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedEcoPointsRouteImport } from './routes/_authenticated/eco-points'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard-users'
import { Route as AuthenticatedDashboardReportsRouteImport } from './routes/_authenticated/dashboard-reports'
import { Route as AuthenticatedDashboardDiversionRouteImport } from './routes/_authenticated/dashboard-diversion'
import { Route as AuthenticatedDashboardAnnouncementsRouteImport } from './routes/_authenticated/dashboard-announcements'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedDashboardRestaurantRouteImport } from './routes/_authenticated/dashboard/restaurant'
import { Route as AuthenticatedDashboardHotelRouteImport } from './routes/_authenticated/dashboard/hotel'
import { Route as AuthenticatedDashboardFarmerRouteImport } from './routes/_authenticated/dashboard/farmer'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWasteReportsRoute =
  AuthenticatedWasteReportsRouteImport.update({
    id: '/waste-reports',
    path: '/waste-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWasteCollectionRoute =
  AuthenticatedWasteCollectionRouteImport.update({
    id: '/waste-collection',
    path: '/waste-collection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrderHistoryRoute =
  AuthenticatedOrderHistoryRouteImport.update({
    id: '/order-history',
    path: '/order-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGisMapRoute = AuthenticatedGisMapRouteImport.update({
  id: '/gis-map',
  path: '/gis-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcoPointsRoute = AuthenticatedEcoPointsRouteImport.update({
  id: '/eco-points',
  path: '/eco-points',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/dashboard-users',
    path: '/dashboard-users',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReportsRoute =
  AuthenticatedDashboardReportsRouteImport.update({
    id: '/dashboard-reports',
    path: '/dashboard-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDiversionRoute =
  AuthenticatedDashboardDiversionRouteImport.update({
    id: '/dashboard-diversion',
    path: '/dashboard-diversion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAnnouncementsRoute =
  AuthenticatedDashboardAnnouncementsRouteImport.update({
    id: '/dashboard-announcements',
    path: '/dashboard-announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRestaurantRoute =
  AuthenticatedDashboardRestaurantRouteImport.update({
    id: '/restaurant',
    path: '/restaurant',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHotelRoute =
  AuthenticatedDashboardHotelRouteImport.update({
    id: '/hotel',
    path: '/hotel',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFarmerRoute =
  AuthenticatedDashboardFarmerRouteImport.update({
    id: '/farmer',
    path: '/farmer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard-announcements': typeof AuthenticatedDashboardAnnouncementsRoute
  '/dashboard-diversion': typeof AuthenticatedDashboardDiversionRoute
  '/dashboard-reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard-users': typeof AuthenticatedDashboardUsersRoute
  '/eco-points': typeof AuthenticatedEcoPointsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/gis-map': typeof AuthenticatedGisMapRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/order-history': typeof AuthenticatedOrderHistoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/waste-collection': typeof AuthenticatedWasteCollectionRoute
  '/waste-reports': typeof AuthenticatedWasteReportsRoute
  '/dashboard/farmer': typeof AuthenticatedDashboardFarmerRoute
  '/dashboard/hotel': typeof AuthenticatedDashboardHotelRoute
  '/dashboard/restaurant': typeof AuthenticatedDashboardRestaurantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard-announcements': typeof AuthenticatedDashboardAnnouncementsRoute
  '/dashboard-diversion': typeof AuthenticatedDashboardDiversionRoute
  '/dashboard-reports': typeof AuthenticatedDashboardReportsRoute
  '/dashboard-users': typeof AuthenticatedDashboardUsersRoute
  '/eco-points': typeof AuthenticatedEcoPointsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/gis-map': typeof AuthenticatedGisMapRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/order-history': typeof AuthenticatedOrderHistoryRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/waste-collection': typeof AuthenticatedWasteCollectionRoute
  '/waste-reports': typeof AuthenticatedWasteReportsRoute
  '/dashboard/farmer': typeof AuthenticatedDashboardFarmerRoute
  '/dashboard/hotel': typeof AuthenticatedDashboardHotelRoute
  '/dashboard/restaurant': typeof AuthenticatedDashboardRestaurantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard-announcements': typeof AuthenticatedDashboardAnnouncementsRoute
  '/_authenticated/dashboard-diversion': typeof AuthenticatedDashboardDiversionRoute
  '/_authenticated/dashboard-reports': typeof AuthenticatedDashboardReportsRoute
  '/_authenticated/dashboard-users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/eco-points': typeof AuthenticatedEcoPointsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/gis-map': typeof AuthenticatedGisMapRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/order-history': typeof AuthenticatedOrderHistoryRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/waste-collection': typeof AuthenticatedWasteCollectionRoute
  '/_authenticated/waste-reports': typeof AuthenticatedWasteReportsRoute
  '/_authenticated/dashboard/farmer': typeof AuthenticatedDashboardFarmerRoute
  '/_authenticated/dashboard/hotel': typeof AuthenticatedDashboardHotelRoute
  '/_authenticated/dashboard/restaurant': typeof AuthenticatedDashboardRestaurantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/reset-password'
    | '/announcements'
    | '/dashboard'
    | '/dashboard-announcements'
    | '/dashboard-diversion'
    | '/dashboard-reports'
    | '/dashboard-users'
    | '/eco-points'
    | '/feed'
    | '/gis-map'
    | '/inventory'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/order-history'
    | '/orders'
    | '/profile'
    | '/requests'
    | '/trades'
    | '/waste-collection'
    | '/waste-reports'
    | '/dashboard/farmer'
    | '/dashboard/hotel'
    | '/dashboard/restaurant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/reset-password'
    | '/announcements'
    | '/dashboard'
    | '/dashboard-announcements'
    | '/dashboard-diversion'
    | '/dashboard-reports'
    | '/dashboard-users'
    | '/eco-points'
    | '/feed'
    | '/gis-map'
    | '/inventory'
    | '/marketplace'
    | '/messages'
    | '/notifications'
    | '/order-history'
    | '/orders'
    | '/profile'
    | '/requests'
    | '/trades'
    | '/waste-collection'
    | '/waste-reports'
    | '/dashboard/farmer'
    | '/dashboard/hotel'
    | '/dashboard/restaurant'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/reset-password'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard-announcements'
    | '/_authenticated/dashboard-diversion'
    | '/_authenticated/dashboard-reports'
    | '/_authenticated/dashboard-users'
    | '/_authenticated/eco-points'
    | '/_authenticated/feed'
    | '/_authenticated/gis-map'
    | '/_authenticated/inventory'
    | '/_authenticated/marketplace'
    | '/_authenticated/messages'
    | '/_authenticated/notifications'
    | '/_authenticated/order-history'
    | '/_authenticated/orders'
    | '/_authenticated/profile'
    | '/_authenticated/requests'
    | '/_authenticated/trades'
    | '/_authenticated/waste-collection'
    | '/_authenticated/waste-reports'
    | '/_authenticated/dashboard/farmer'
    | '/_authenticated/dashboard/hotel'
    | '/_authenticated/dashboard/restaurant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/waste-reports': {
      id: '/_authenticated/waste-reports'
      path: '/waste-reports'
      fullPath: '/waste-reports'
      preLoaderRoute: typeof AuthenticatedWasteReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/waste-collection': {
      id: '/_authenticated/waste-collection'
      path: '/waste-collection'
      fullPath: '/waste-collection'
      preLoaderRoute: typeof AuthenticatedWasteCollectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/order-history': {
      id: '/_authenticated/order-history'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof AuthenticatedOrderHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gis-map': {
      id: '/_authenticated/gis-map'
      path: '/gis-map'
      fullPath: '/gis-map'
      preLoaderRoute: typeof AuthenticatedGisMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eco-points': {
      id: '/_authenticated/eco-points'
      path: '/eco-points'
      fullPath: '/eco-points'
      preLoaderRoute: typeof AuthenticatedEcoPointsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-users': {
      id: '/_authenticated/dashboard-users'
      path: '/dashboard-users'
      fullPath: '/dashboard-users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-reports': {
      id: '/_authenticated/dashboard-reports'
      path: '/dashboard-reports'
      fullPath: '/dashboard-reports'
      preLoaderRoute: typeof AuthenticatedDashboardReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-diversion': {
      id: '/_authenticated/dashboard-diversion'
      path: '/dashboard-diversion'
      fullPath: '/dashboard-diversion'
      preLoaderRoute: typeof AuthenticatedDashboardDiversionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-announcements': {
      id: '/_authenticated/dashboard-announcements'
      path: '/dashboard-announcements'
      fullPath: '/dashboard-announcements'
      preLoaderRoute: typeof AuthenticatedDashboardAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/restaurant': {
      id: '/_authenticated/dashboard/restaurant'
      path: '/restaurant'
      fullPath: '/dashboard/restaurant'
      preLoaderRoute: typeof AuthenticatedDashboardRestaurantRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/hotel': {
      id: '/_authenticated/dashboard/hotel'
      path: '/hotel'
      fullPath: '/dashboard/hotel'
      preLoaderRoute: typeof AuthenticatedDashboardHotelRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/farmer': {
      id: '/_authenticated/dashboard/farmer'
      path: '/farmer'
      fullPath: '/dashboard/farmer'
      preLoaderRoute: typeof AuthenticatedDashboardFarmerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardFarmerRoute: typeof AuthenticatedDashboardFarmerRoute
  AuthenticatedDashboardHotelRoute: typeof AuthenticatedDashboardHotelRoute
  AuthenticatedDashboardRestaurantRoute: typeof AuthenticatedDashboardRestaurantRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardFarmerRoute: AuthenticatedDashboardFarmerRoute,
    AuthenticatedDashboardHotelRoute: AuthenticatedDashboardHotelRoute,
    AuthenticatedDashboardRestaurantRoute:
      AuthenticatedDashboardRestaurantRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedDashboardAnnouncementsRoute: typeof AuthenticatedDashboardAnnouncementsRoute
  AuthenticatedDashboardDiversionRoute: typeof AuthenticatedDashboardDiversionRoute
  AuthenticatedDashboardReportsRoute: typeof AuthenticatedDashboardReportsRoute
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedEcoPointsRoute: typeof AuthenticatedEcoPointsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGisMapRoute: typeof AuthenticatedGisMapRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOrderHistoryRoute: typeof AuthenticatedOrderHistoryRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedWasteCollectionRoute: typeof AuthenticatedWasteCollectionRoute
  AuthenticatedWasteReportsRoute: typeof AuthenticatedWasteReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedDashboardAnnouncementsRoute:
    AuthenticatedDashboardAnnouncementsRoute,
  AuthenticatedDashboardDiversionRoute: AuthenticatedDashboardDiversionRoute,
  AuthenticatedDashboardReportsRoute: AuthenticatedDashboardReportsRoute,
  AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
  AuthenticatedEcoPointsRoute: AuthenticatedEcoPointsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGisMapRoute: AuthenticatedGisMapRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOrderHistoryRoute: AuthenticatedOrderHistoryRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedWasteCollectionRoute: AuthenticatedWasteCollectionRoute,
  AuthenticatedWasteReportsRoute: AuthenticatedWasteReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
